# name
name: ci

# triggers
on:
  workflow_dispatch:
    example-value:
      description: 'Number of Octocats'
      required: false
      default: '1'
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
  pull_request:

jobs:
  check:
    uses: cidverse/catalog/.github/workflows/shared-ci.yml@main
    with:
      cid-workflow: main
      cid-version: latest
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # info
  event:
    name: Event
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
          cat $GITHUB_EVENT_PATH
