# name
name: ci

# triggers
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: Log level
        required: true
        default: info
        type: choice
        options:
          - debug
          - info
          - warn
          - error
  push:
    branches:
      - main
    tags:
      - v*.*.*
    paths-ignore:
      - README.md
      - LICENSE
      - .github/**
      - .gitignore
      - .editorconfig
      - renovate.json
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .github/**
      - .gitignore
      - .editorconfig
      - renovate.json

jobs:
  check:
    uses: cidverse/catalog/.github/workflows/shared-ci.yml@main
    with:
      cid-workflow: main
      cid-version: latest
      cid-loglevel: ${{ github.event.inputs.loglevel }}
      egress-policy: block
      egress-allowed-endpoints: >-
        api.github.com:443
        github.com:443
        objects.githubusercontent.com:443
        raw.githubusercontent.com:443
        quay.io:443
        cdn01.quay.io:443
        cdn02.quay.io:443
        cdn03.quay.io:443
      egress-allowed-endpoints-scan: >-
        scanner.sonarcloud.io:443
        semgrep.dev:443
        sonarcloud.io:443
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}