# name
name: release

# triggers
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

permissions:
  contents: read

# jobs
jobs:
  # info
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: info
        run: |
          echo "> project modules"
          cid module ls
          echo "> catalog"
          cid catalog list
          echo "> workflows"
          cid workflow ls
  # build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          cid workflow run --stage build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test
        run: |
          cid workflow run --stage test
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # scan
  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > test
        uses: actions/download-artifact@v3
        with:
          name: test-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          cid workflow run --stage scan
  # package
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: package
        run: |
          cid workflow run --stage package
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # publish
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build, package]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: package-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cid workflow run --stage publish
