# name
name: check

# triggers
on:
  workflow_call:
    inputs:
      cid-workflow:
        required: true
        type: string
    secrets:
      # qodana
      QODANA_TOKEN:
        required: false
      # sonarcloud
      SONAR_HOST_URL:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_ORGANIZATION:
        required: false

# permissions, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions and https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
permissions:
  contents: read

# jobs
jobs:
  # info
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: info
        run: |
          echo "> project modules"
          cid module ls
          echo "> catalog"
          cid catalog list
          echo "> workflows"
          cid workflow ls
  # build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
        run: |
          cid workflow run "$CID_WORKFLOW" --stage build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
        run: |
          cid workflow run "$CID_WORKFLOW" --stage test
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # scan
  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > test
        uses: actions/download-artifact@v3
        with:
          name: test-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: scan
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          cid workflow run "$CID_WORKFLOW" --stage scan
  # package
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: package
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
        run: |
          cid workflow run "$CID_WORKFLOW" --stage package
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
  # publish
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build, package]
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > build
        uses: actions/download-artifact@v3
        with:
          name: package-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: publish
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cid workflow run "$CID_WORKFLOW" --stage publish
